/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package travel.agencies;

import org.junit.Test;
import travel.agencies.products.DiscountProduct;
import travel.agencies.products.Product;
import travel.agencies.products.Program;
import travel.agencies.products.SimpleProduct;

import java.time.LocalDate;
import java.util.*;

import static java.time.LocalDate.of;
import static org.junit.Assert.*;

public class LibraryTest {

    static SortedSet<String> locations =
            new TreeSet<>(List.of(
                    "Acores",
                    "Lisboa",
                    "Madeira",
                    "Porto"
            ));

    static SortedSet<Product> productDb;

    static {
        SimpleProduct acores =
                new SimpleProduct(
                        "Acores",
                        of(2012,3,1),
                        of(2012,3,14), 700);

        SimpleProduct madeira =
                new SimpleProduct(
                        "Madeira",
                        of(2012,3,15),
                        of(2012,3,22), 525);
        Product packIslands =
                new Program("Descubra Acores e Madeira", acores, madeira);
        Product vLisbon =
                new SimpleProduct( "Lisboa",
                        LocalDate.of(2012,3,23),
                        LocalDate.of(2012,3,30), 600);

        Product packPortugal =
                new Program("Portugal e ilhas",packIslands,vLisbon);

        Product promoAcores = new DiscountProduct(acores, 30);


        productDb = new TreeSet<>();
        productDb.add(acores);
        productDb.add(madeira);
        productDb.add(packIslands);
        productDb.add(vLisbon);
        productDb.add(packPortugal);
        productDb.add(promoAcores);
    }

    public Product getByName(String name) {
        return productDb.stream()
                .filter(p -> p.getName().equalsIgnoreCase(name))
                .findFirst().get();
    }



    @Test
    public void testProgramPrice() {
        Product vAcores = getByName("Acores");

        Product vMadeira = getByName("Madeira");


        Product pack1 = getByName("Descubra Acores e Madeira");

        double expectedPrice = vMadeira.getPrice()+vAcores.getPrice();
        assertEquals(pack1.getPrice(),expectedPrice, 0.01 );

        System.out.println(pack1);
    }

    @Test
    public void testProgramDescription() {
        String expectedDescription =
                "de 2012-03-01 a 2012-03-30, Portugal e ilhas\n" +
                "  de 2012-03-01 a 2012-03-22, Descubra Acores e Madeira\n" +
                "    de 2012-03-01 a 2012-03-14, Acores, 700€\n" +
                "    de 2012-03-15 a 2012-03-22, Madeira, 525€\n" +
                "  TOTAL: 1225€\n" +
                "  de 2012-03-23 a 2012-03-30, Lisboa, 600€\n" +
                "TOTAL: 1825€";

        Product packPortugal = getByName("Portugal e ilhas");

        System.out.println(packPortugal);
        System.out.println(expectedDescription);
        assertEquals(expectedDescription, packPortugal.toString());

    }


    @Test
    public void countSimpleProductsInProductsDb() {
        int expectedSimpleCount = 9;

        int actualCount = Product.totalSimpleProducts(productDb);
        assertEquals(expectedSimpleCount, actualCount);
    }


    @Test
    public void discountedAcoresTest() {
        Product promoAcores = getByName("Promo Acores");
        System.out.println(promoAcores);
    }

}
