/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package travel.agencies;

import org.junit.Test;
import travel.agencies.products.Product;
import travel.agencies.products.Program;
import travel.agencies.products.SimpleProduct;

import java.time.LocalDate;
import static java.time.LocalDate.of;
import static org.junit.Assert.*;

public class AgenciesTest {
    /*
    @Test
    public void testProgramDates() {
        SimpleProduct vAcores =
        new SimpleProduct(
                "Açores",
                of(2012,3,1),
                of(2012,3,14), 700);

        SimpleProduct vMadeira =
                new SimpleProduct(
                        "Madeira",
                        of(2012,3,15),
                        of(2012,3,22), 525);

        Product pack1 =
                new Program("Portugal e Ilhas",
                        vMadeira, vAcores);

        double expectedPrice = vMadeira.getPrice()+vAcores.getPrice();
        assertEquals(pack1.getPrice(),expectedPrice, 0.01 );

        System.out.println(pack1);
    }
    */

}
